name: Publish

on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Publish Binaries
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-03-25
          override: true
      - name: Build Corrs Package
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --package corrs
      - name: Build corr Package
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --package corr

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: yarn
        working-directory: ./frontend

      - name: Create bundle
        run: yarn build
        working-directory: ./frontend

      - name: Run Gulp Task to Shrink Bundle
        run: yarn gulp
        working-directory: ./frontend


      - name: Compress corrs package
        uses: master-atul/tar-action@v1.0.2
        id: compress-corrs
        with:
          command: c
          cwd: target/release
          files: |
            corrs
            index.html
          outPath: corrs.tar.gz
      - name: Compress corr package
        uses: master-atul/tar-action@v1.0.2
        id: compress-corr
        with:
          command: c
          cwd: target/release
          files: |
            corr
          outPath: corr.tar.gz

      - name: Upload Corrs binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: corrs.tar.gz
          asset_name: corrs.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload corr binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: corr.tar.gz
          asset_name: corr.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update Corrs formula
        uses: mislav/bump-homebrew-formula-action@v1.6
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          homebrew-tap: atmnk/homebrew-corr
          formula-name: corrs
          download-url:  ${{format('{0}{1}{2}', 'https://github.com/atmnk/corr/releases/download/', steps.get_version.outputs.VERSION , '/corrs.tar.gz')}}
          commit-message: 'Bump up {{formulaName}} formula to v{{version}} version'

      - name: Update corr formula
        uses: mislav/bump-homebrew-formula-action@v1.6
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          homebrew-tap: atmnk/homebrew-corr
          formula-name: corr
          download-url: ${{format('{0}{1}{2}', 'https://github.com/atmnk/corr/releases/download/', steps.get_version.outputs.VERSION , '/corr.tar.gz')}}
          commit-message: 'Bump up {{formulaName}} formula to v{{version}} version'
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: atmnk/corr # defaults to current repo
          keep_latest: 3
          delete_tag_pattern: beta # defaults to ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
