name: Build Windows
on:
  push:
    tags:
      - 'k*'
jobs:
  build:
    runs-on: windows-latest
    name: Test The Commit
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo 1.0.4)
      - name: Print Version
        run: |
        echo ${{ format('target/wix/corr-{0}-x86_64.msi', steps.get_version.outputs.VERSION) }}
