name: Publish Beta

on:
  push:
    tags:
      - 'ub*'
jobs:
  build:
    name: Publish Binaries For Beta
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build corr Package
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --package corr
      - name: Script To create Debian Package
        run: |
          mkdir -p .debpkg/usr/bin
          mkdir -p .debpkg/usr/lib/corr
          cp target/release/corr .debpkg/usr/bin/corr
          chmod +x .debpkg/usr/bin/corr
          echo -e "a=1" > .debpkg/usr/lib/corr/corr.conf
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c3-)
      - uses: jiro4989/build-deb-action@v2
        id: bundle_debian
        with:
          package: corr
          package_root: .debpkg
          maintainer: Atmaram
          version: ${{steps.get_version.outputs.VERSION}}
          arch: 'amd64'
          desc: 'Corr Binaries'
      - name: Upload corr binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{steps.bundle_debian.outputs.file_name}}
          asset_name: ${{steps.bundle_debian.outputs.file_name}}
          tag: ${{ github.ref }}
          overwrite: true
