name: Build Windows
on:
  push:
    tags:
      - 'w*'

  
jobs:
  build:
    runs-on: windows-latest
    name: Test The Commit
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: cargo-wix
          override: true
      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: wix
          args: --package corr

      - name: Upload corr binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/wix/corr-1.0.4-x86_64.msi
          asset_name: corr-1.0.4-x86_64.msi
          tag: ${{github.event.inputs.version}}
          overwrite: true
