name: Build Windows
on:
  push:
    tags:
      - 'w*'

  
jobs:
  build:
    runs-on: windows-latest
    name: Test The Commit
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-wix
          version: latest
          use-tool-cache: true
      - name: Build Binary
        uses: actions-rs/cargo@v1
        with:
          command: wix
          args: --package corr
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | cut -c2-)
      - name: Upload corr binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/wix/corr-${{steps.get_version.outputs.VERSION}}-x86_64.msi'
          asset_name: 'corr-${{steps.get_version.outputs.VERSION}}-x86_64.msi'
          tag: ${{ github.ref }}
          overwrite: true
